[tool.poetry]
name = "integral"
version = "0.1.0"
description = "Integrational test tool"
authors = ["becash <admin@ci.md>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
